In [35]:
import numpy as np


In [36]:
print(f'numpy version: {np.__version__}')

numpy version: 2.0.0


In [37]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [38]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [39]:
len(dir(np))

530

In [40]:
print(np.log(2))

0.6931471805599453


In [41]:
print(np.not_equal(10,10))

False


Creating numpy array using

Creating int numpy arrays

creating python list using list function


one dimensional list 

In [42]:
python_list=[1,2,3,4,5,6]
print(type(python_list))
print(python_list)

<class 'list'>
[1, 2, 3, 4, 5, 6]


creating numpy array list using python list


In [43]:
numpy_array_from_list=np.array(python_list)
print(numpy_array_from_list)
print(type(numpy_array_from_list))

print(numpy_array_from_list.ndim)

print(numpy_array_from_list.size)

print(numpy_array_from_list.shape)

print(numpy_array_from_list.reshape(2,3))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
6
(6,)
[[1 2 3]
 [4 5 6]]


creating python  list using  numpy array list

In [44]:
python_list_from_array=numpy_array_from_list.tolist()
print(f'one dimensional list from numpy array :{python_list_from_array}')

print(type(python_list_from_array))

print(python_list_from_array.ndim)

print(python_list_from_array.size)

print(python_list_from_array.shape)


one dimensional list from numpy array :[1, 2, 3, 4, 5, 6]
<class 'list'>


AttributeError: 'list' object has no attribute 'ndim'

**because  "numpy array list" converted to "python list : hence python list does not have these methods**

TWO DIMENSIONAL LIST:-

1.which is an python two dimensional list 

In [ ]:
two_dimensional_list=[[1,2,3],[4,5,6],[7,8,9]]
print(type(two_dimensional_list))
print(two_dimensional_list)

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


2.converting to numpy two dimensional array list


In [ ]:
np_two_dimensional_array_list=np.array(two_dimensional_list)
print(np_two_dimensional_array_list)
print(type(np_two_dimensional_array_list))

print(np_two_dimensional_array_list.ndim)
print(np_two_dimensional_array_list.size)
print(np_two_dimensional_array_list.shape)
print(np_two_dimensional_array_list.reshape(3,3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
9
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Creating float numpy arrays

Creating a float numpy array from list with a float data type parameter

In [ ]:
python_list=[1,2,3,4,5,6,7]
np_array_list=np.array(python_list,dtype=float)
print(np_array_list)

[1. 2. 3. 4. 5. 6. 7.]


In [ ]:
python_list=[1,0,-1,0,0,-1]
np_array_list1=np.array(python_list,dtype=bool)
print(np_array_list1)

[ True False  True False False  True]


In [ ]:
python_list_from_np=np_two_dimensional_array_list.tolist()
print(f'two dimensional list from numpy array: {python_list_from_np}')

two dimensional list from numpy array: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Creating numpy array from tuple

Numpy array  from tuple

In [ ]:
#creating python tuple
python_tuple=(1,2,3,4,5)
print(python_tuple)
print(type(python_tuple))

(1, 2, 3, 4, 5)
<class 'tuple'>


In [ ]:
numpy_array_from_tuple=np.array(python_tuple)
print(type(numpy_array_from_tuple))
print(numpy_array_from_tuple)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
tuple_from_numpy=numpy_array_from_tuple.totuple()
print(tuple_from_numpy)

AttributeError: 'numpy.ndarray' object has no attribute 'totuple'

Shape of numpy array:-

**the shape method provide the shape of the array as tuple.the first is the row and the second is column. if the array is just one D it returns the size of array**

In [ ]:
nums=np.array([1,2,3,4,5,6,7])
print(type(nums))
print(nums)
print(f'the shape of nums is :{nums.shape}')

two_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_array)
print(type(two_array))
print(f'the shape of the two dimensional array is : {two_array.shape}')

four_by_three_array_shape=np.array([[1,2,3],[4,5,6],[7,8,9],[0,9,1]])
print(four_by_three_array_shape)
print(type(four_by_three_array_shape))
print(f'the shape of the array is : {four_by_three_array_shape.shape}')

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]
the shape of nums is :(7,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
the shape of the two dimensional array is : (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 9 1]]
<class 'numpy.ndarray'>
the shape of the array is : (4, 3)


In [ ]:
three_by_four_array = np.array([[0, 1, 2, 3],
        [4,5,6,7],
        [8,9,10, 11]])
print(three_by_four_array.shape)

(3, 4)


**Data Types of Numpy**

types of data types : str , int , float , none,bool,list , complex

In [ ]:
int_lists=[-3,-2,-1,0,1,2,3]
int_array=np.array(int_lists)
int_float=np.array(int_lists,dtype=float)


print(int_array)
print(int_array.dtype)
print(int_float)
print(int_float.dtype)

[-3 -2 -1  0  1  2  3]
int64
[-3. -2. -1.  0.  1.  2.  3.]
float64


**size of the Numpy Array**

In numpy to know the number of items in a  numpy array list we use **size**

In [ ]:
numpy_array_from_list=np.array([1,2,3,4,5,6])
print(numpy_array_from_list)
print(type(numpy_array_from_list))
print(f'the shape of the array list is : {numpy_array_from_list.size}')

two_dimension_list=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_dimension_list)
print(type(two_dimension_list))
print(f'the shape of the array is : {two_dimension_list.size}')

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
the shape of the array list is : 6
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
the shape of the array is : 9


MATHEMATICAL OPERATIONS IN NUMPY:-

numpy array is not exactly like python list.To do mathematical operations in python list we have to loop through the items but numpy can allow to do any mathematical operations without looping.

Addition (+)

Subtraction (-)

Multiplication (*)

Division (/)

Modules (%)

Floor Division(//)

Exponential(**)


1.ADDITION

In [ ]:
numpy_array_from_list=np.array([1,2,3,4,5])
print(f'original arrray: {numpy_array_from_list}')
ten_plus_list=numpy_array_from_list + 10
print(f'adding list is : {ten_plus_list}')

original arrray: [1 2 3 4 5]
adding list is : [11 12 13 14 15]


In [ ]:
a=10
b=30
print(np.add(a,b))

40


2.SUBTRACTION

In [ ]:
numpy_array_from_list=np.array([1,2,3,4,5])
print(f'original array : {numpy_array_from_list}')
ten_minus=numpy_array_from_list-10
print(ten_minus)

original array : [1 2 3 4 5]
[-9 -8 -7 -6 -5]


In [ ]:
a=10
b=5
print(np.subtract(a,b))

5


MULTIPLICATION

In [ ]:
numpy_array_from_list=np.array([1,2,3,4,5])
print(f'original array : {numpy_array_from_list}')
ten_times=numpy_array_from_list*10
print(ten_times)

original array : [1 2 3 4 5]
[10 20 30 40 50]


In [ ]:
a=10
b=20
print(np.multiply(a,b))

200


In [ ]:
a=np.array([[1,2],[4,5]])
b=np.array([[5],[10]])
print(np.matmul(a,b))

[[25]
 [70]]


4.DIVISION


In [ ]:
numpy_array_from_list=np.array([1,2,3,4,5])
print(f'original array: {numpy_array_from_list}')
ten_divison=numpy_array_from_list/10
print(f'divide by ten : {ten_divison}')

original array: [1 2 3 4 5]
divide by ten : [0.1 0.2 0.3 0.4 0.5]


5.MODULUS:-

In [ ]:
numpy_array_from_list=np.array([1,2,3,4,5])
print(f'originl array : {numpy_array_from_list}')
ten_modulus=numpy_array_from_list%3
print(f'module by 10 : {ten_modulus}')

originl array : [1 2 3 4 5]
module by 10 : [1 2 0 1 2]


FLOOR DIVISION:-

In [ ]:
array_list=np.array([1,2,3,4,5,6,7])
print(f'original list : {array_list}')
floor=array_list//5
print(f'fllor division array is {floor}')

original list : [1 2 3 4 5 6 7]
fllor division array is [0 0 0 0 1 1 1]


EXPONENTIAL

In [ ]:
np=np.array([1,2,3,4,5,6,6])
print(f'original list {np}')
expo=np**2
print(expo)

original list [1 2 3 4 5 6 6]
[ 1  4  9 16 25 36 36]


CHECKING DATA TYPES

In [ ]:
p_int_array =   np.array([1,2,3,4,5])
p_array_float= np.array([1.1,2.1,3.1,4.5,6.0])
p_array_bool= np.array([-3,-2,-1,0,1,2,3],dtype=bool)

print(p_int_array)
print(p_array_float)
print(p_array_bool)

print(p_int_array.dtype)
print(p_array_float.dtype)
print(p_array_bool.dtype)


[1 2 3 4 5]
[1.1 2.1 3.1 4.5 6. ]
[ True  True  True False  True  True  True]
int64
float64
bool


In [ ]:
#Int,  Float numbers
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int64
float64
bool


CONVERTING DATA TYPES:-

we can convert data types of numpy array

1.INT TO FLOAT

In [ ]:
numpy_int_arr=np.array([1,2,3,4,5],dtype=float)
numpy_int_arr

array([1., 2., 3., 4., 5.])

2.FLOAT TO INT:-

In [ ]:
numpy_float=np.array([1.1,2.3,4.5,6.7,8.9],dtype=int)
numpy_float

array([1, 2, 4, 6, 8])

INT TO BOOLEAN

In [ ]:
bool=np.array([-3,-2,-1,0,1,2,3],dtype=bool)
print(bool)

[ True  True  True False  True  True  True]


INT TO STRING

In [ ]:
string=bool.astype('int').astype('str')
string

array(['1', '1', '1', '0', '1', '1', '1'], dtype='<U21')

MULTI-DIMENSIONAL-ARRAY

In [ ]:
two_dimensional_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_dimensional_array)
print(type(two_dimensional_array))


print(f'shape is : {two_dimensional_array.shape}')
print(f'size is : {two_dimensional_array.size}')
print(f'dimensions is : {two_dimensional_array.ndim}')
print(f'matrix form is : {two_dimensional_array.reshape(9,1)}')
print(f'data type is : {two_dimensional_array.dtype}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
shape is : (3, 3)
size is : 9
dimensions is : 2
matrix form is : [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
data type is : int64


GETTING ITEM FROM NUMPY ARRAY:-

In [ ]:
np_two_dimensional_array_list=np.array([[1,2,3],[4,5,6],[7,8,9]])


first_row=np_two_dimensional_array_list[0]
second_row=np_two_dimensional_array_list[1]
third_row=np_two_dimensional_array_list[2]

print(f'first row : {first_row}')
print(f'second_row : {second_row}')
print(f'third row : {third_row}')

first row : [1 2 3]
second_row : [4 5 6]
third row : [7 8 9]


In [ ]:
first_column=np_two_dimensional_array_list[:,0]
second_column=np_two_dimensional_array_list[:,1]
third_column=np_two_dimensional_array_list[:,2]

print(f'first column : {first_column}')
print(f'second column : {second_column}')
print(f'third_column : {third_column}')


first column : [1 4 7]
second column : [2 5 8]
third_column : [3 6 9]


SLICING NUMPY ARRAY:-

slicing in numpy is similar to slicing in python list:-

In [ ]:
np_list=np.array([[1,2,3],[4,5,6],[7,8,9]])
first_two_rows_and_columns=np_list[0:2,0:2]
print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


In [ ]:
rows_2=np_list[0:3,0:3]
rows_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

How to reverse the rows and the whole array?

two_dimension_array[::]

In [ ]:
np_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
np_array[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
np_array[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np_array[0,::-1]

array([6, 5, 4])

In [ ]:
np_array[1,::-1]

array([6, 5, 4])

In [ ]:
np_array[2,::-1]

array([9, 8, 7])

In [ ]:
np_array[::-1,0]

array([7, 4, 1])

In [ ]:
np_array[::-1,1]

array([8, 5, 2])

In [ ]:
np_array[::-1,2]

array([9, 6, 3])

How to represent missing values ?

In [ ]:
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np_array[0,1]=87

In [ ]:
np_array[1,1]=55

In [ ]:
np_array[1,2]=89

In [ ]:
print(np_array)

[[ 1 87  3]
 [ 4 55 89]
 [ 7  8  9]]


ZEROS

In [ ]:
#numpy zeros
numpy_zeros=np.zeros((3,3),dtype=int,order='C')
print(numpy_zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
numpy_zeros=np.zeros((3,3),dtype=float)
numpy_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

ONES:-

In [ ]:
numpy_ones=np.ones((3,3),dtype=float)
numpy_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
numpy_ones=np.ones((3,3),dtype=int)
numpy_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
twoes=numpy_ones*2

In [ ]:
twoes

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

FULL

In [ ]:
numpy_ones=np.full((3,4),7)

In [ ]:
numpy_ones

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
numpy_ones=np.full((2,2),4)
numpy_ones

array([[4, 4],
       [4, 4]])

EYE

In [ ]:
numpy_ones=np.eye(3,dtype=int)
numpy_ones

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**RESHAPE**

In [ ]:
#reshape
numpy_array=np.array([[1,2,3],[4,5,6]])
print(f'orginal array  : {numpy_array}')

reshaped=numpy_array.reshape(3,2)
print(f'reshaped array is :{reshaped}')

orginal array  : [[1 2 3]
 [4 5 6]]
reshaped array is :[[1 2]
 [3 4]
 [5 6]]


**FLATTEND**

In [ ]:
flattened=reshaped.flatten()
print(flattened)

[1 2 3 4 5 6]


**HORIZONTAL STACK**

In [ ]:
##horizontal stack
np_list_one=np.array([1,2,3])
np_list_two=np.array([4,5,6])
print(np.add(np_list_one,np_list_two))


print(f'horizontal stack is : {np.hstack((np_list_one,np_list_two))}')

[5 7 9]
horizontal stack is : [1 2 3 4 5 6]


In [ ]:
#vertical stack
print(f'vertical stack is : {np.vstack((np_list_one,np_list_two))}')

vertical stack is : [[1 2 3]
 [4 5 6]]


**GENERATING RANDOM NUMBERS**:-

In [ ]:
#generate a random float number
random_float=np.random.random()
random_float

0.40187331987849684

In [ ]:
#generating random float number
random_float=np.random.random(5)
print(random_float)

[0.11033464 0.12372735 0.76850823 0.84251496 0.61980868]


In [ ]:
#generating a random integers from 0,10
random_int=np.random.randint(0,10)
print(random_int)

3


In [ ]:
a=np.random.randint(10,50,6)  # where 6 is the how many numbers you want randomly
print(a)

[22 21 13 13 34 12]


In [ ]:
a=np.random.randint(2,10,size=4)
print(a)

[2 6 4 5]


In [ ]:
a=np.random.randint(1,10,size=(3,3))

In [ ]:
print(a)

[[8 9 2]
 [1 8 8]
 [9 9 1]]


**Generating random numbers** by using normal functions

In [ ]:
#np.random.normal(mul,sigma,size)
a=np.random.normal(100,15,80)
print(a)

[126.71238124 103.52752355  99.89126071 102.72069156  98.27694585
 109.38238282 105.45986653 103.67400938  92.14364632 104.86301218
 104.61015798  83.20993566  92.50168354 108.50120574  99.15513633
  79.23972435 102.03239843 120.10020553  94.03939295 107.79397152
 105.37349278 113.3485019   97.06569237  61.65407458  89.02374233
 120.91337889 103.98620398 104.74896565  77.30066561 109.5556879
  96.78681998  80.09353757  89.79025594 107.69658614 119.88633541
  93.10901294  85.68653563 121.82297554 104.8169904  123.11309679
  95.488927    93.33622104 110.83664694  84.86259533  83.02602903
 106.3446538  106.8441506  126.86131472 112.97785967  69.55363951
  93.67215989  98.84234987  83.66808045 101.06056842 106.64297624
  99.60652287 128.84357608  88.78240687  85.79182616 101.56517296
  87.03088904  94.48818134  67.15471026  98.6541178  114.0533622
 108.70631642  97.68768028 107.15563561  84.44371487 126.93230597
  96.09375134 109.5891232  114.31266126  84.45151026 101.24976297
  81.0046403

MATRIX IN NUMPY

In [ ]:
three_two_matrix=np.matrix(np.ones((3,2),dtype=int))

In [ ]:
three_two_matrix

matrix([[1, 1],
        [1, 1],
        [1, 1]])

In [ ]:
seven_seven=np.matrix(np.full(((7,7),8),dtype=int))

TypeError: full() missing 1 required positional argument: 'fill_value'

In [ ]:
zero_matrix=np.matrix(np.zeros((7,7),dtype=int))

In [ ]:
zero_matrix

matrix([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.asarray(zero_matrix)[6]=9

In [ ]:
zero_matrix

matrix([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [9, 9, 9, 9, 9, 9, 9]])

Numpy numpy.arange()

sometimes you want to create values that are evenly spaced within a defined interval.for instance ,you want to create values from 1 to 10;you can use numpy.arange()function

In [ ]:
#similar to range arrange numpy.arange(start,stop,step)
a=np.arange(0,10,1)
print(f'whole numbers is : {a} ')

whole numbers is : [0 1 2 3 4 5 6 7 8 9] 


In [ ]:
a=np.arange(1,11,1)
print(f'natural numbers is : {a}')


natural numbers is : [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=np.arange(1,11,2)
print(f'odd numbers is {a}')

odd numbers is [ 1  4  7 10]


In [ ]:
a=np.arange(2,20,2)
print(f'even numbers is {a}')

even numbers is [ 2  4  6  8 10 12 14 16 18]


Creating sequence of numbers using linspace

In [ ]:
#numpy.linspace()
#numpy.logspace() in python example
#for instance,it can be used to create 10 values from 1 to 5 evenly based
a=np.linspace(10,20,9)
print(a)

[10.   11.25 12.5  13.75 15.   16.25 17.5  18.75 20.  ]


In [ ]:
b=np.linspace(1.0,5.0,num=10)
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
#not to include the last value
c=np.linspace(1.0,5.0,num=5,endpoint=False)
print(c)

[1.  1.8 2.6 3.4 4.2]


In [ ]:
#logspace
# logspce returns even spaced numbers on alog scale.logspace has the same parameters as linspace

#numpy.logspace(start,stop,num,endpoint)

a=np.logspace(2,4.0,num=8)
print(a)


[  100.           193.06977289   372.75937203   719.685673
  1389.49549437  2682.69579528  5179.47467923 10000.        ]


In [ ]:
#to check the size of the array
a=np.array([1,2,3],dtype=int)
print(a)

[1 2 3]


In [ ]:
a.itemsize

8

INDEXING:-

In [ ]:
a=np.array([[1,2,4],[5,6,7]])
print(a)
print(f'the first row is {a[0]}')
print(f'the second row is {a[1]}')


print(f'the first column is {a[:,0]}')
print(f'the second column is {a[:,1]}')
print(f'the third column is {a[:,2]}')

[[1 2 4]
 [5 6 7]]
the first row is [1 2 4]
the second row is [5 6 7]
the first column is [1 5]
the second column is [2 6]
the third column is [4 7]


In [ ]:
a=np.array([[10,1,22],[25,8,3],[55,7,3]])
print(a)
print('====ROW===')
print(f'maximun is:{np.max(a,axis=1)}')
print(f' minimum is :{np.min(a,axis=1)}')
print(f'sum is :{np.sum(a,axis=1)}')
#arg max n min is giving the indexes values
print(f'arg max is :{np.argmax(a,axis=1)}')  
print(f'arg min is{np.argmin(a,axis=1)}')
print(f'the meean is {np.mean(a,axis=1)}')
print(f'the median is {np.median(a,axis=1)}')


print("===column===")
print(f'the minimum is {np.min(a,axis=0)}')
print(f'the maximum is {np.max(a,axis=0)}')
print(f'the sum is {np.max(a,axis=0)}')
print(f'the mean is {np.mean(a,axis=0)}')
print(f'the median is {np.median(a,axis=0)}')
print(f'the arg max is {np.argmax(a,axis=0)}')
print(f'the arg min is {np.argmin(a,axis=0)}')


[[10  1 22]
 [25  8  3]
 [55  7  3]]
====ROW===
maximun is:[22 25 55]
 minimum is :[1 3 3]
sum is :[33 36 65]
arg max is :[2 0 0]
arg min is[1 2 2]
the meean is [11.         12.         21.66666667]
the median is [10.  8.  7.]
===column===
the minimum is [10  1  3]
the maximum is [55  8 22]
the sum is [55  8 22]
the mean is [30.          5.33333333  9.33333333]
the median is [25.  7.  3.]
the arg max is [2 1 0]
the arg min is [0 0 1]


In [ ]:
#transpose

a=np.array([[1,2,3],[4,5,6]])
print(f'original matrix:{a}')
b=a.T
print(f'transpose matrix:{b}')

original matrix:[[1 2 3]
 [4 5 6]]
transpose matrix:[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#ravel any dimension will change to 1D:-
a=np.array([[1,2,3],[4,5,6]])
print(f'original:{a}')
print(f'dimensions is :{a.ndim}')
b=a.ravel()
print(b)
print((f'dimension is {b.ndim}'))
      

original:[[1 2 3]
 [4 5 6]]
dimensions is :2
[1 2 3 4 5 6]
dimension is 1


In [ ]:
#cocatination

a=np.array([[1,2,3],[4,5,6]])
print(f'a matrix is {a}')

b=np.array([[7,8,9],[10,4,6]])
print(f'b matrix is {b}'  )

c=np.concatenate((a,b))
print(f'c matrix is {c}')

a matrix is [[1 2 3]
 [4 5 6]]
b matrix is [[ 7  8  9]
 [10  4  6]]
c matrix is [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10  4  6]]


In [ ]:
#diag opr diagonal

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(f'diagonal matrix is {np.diag(a)}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal matrix is [1 5 9]


**How to create repeating sequences?**

In [ ]:
a=[1,2,3]
#  TILE repeat whole of 'a' two times

print(f'Tile  is: {np.tile(a,3)}')

#repeat each element of  a 2times

print(f'Repeat is: {np.repeat(a,3)}')

Tile  is: [1 2 3 1 2 3 1 2 3]
Repeat is: [1 1 1 2 2 2 3 3 3]


In [ ]:
random=np.random.random(1)
print(random)

[0.82712728]


In [ ]:
a=np.random.random(size=[2,3])
print(a)

[[0.57182482 0.95214582 0.87990501]
 [0.39789289 0.51595258 0.99071765]]


In [ ]:
b=(np.random.choice([1,2,3,4,5,6],size=4))
print(b)

[3 5 6 1]


In [ ]:
print(b)

[3 5 6 1]


In [ ]:
b

array([6, 2, 2, 3])

In [ ]:
print(np.random.choice(['a','e','i','o','u'],size=10))

['i' 'u' 'i' 'e' 'a' 'u' 'u' 'a' 'o' 'u']


In [ ]:
rand=np.random.rand(2,2)
print(rand)

[[0.86831966 0.07232997]
 [0.07842462 0.3181534 ]]


In [ ]:
rand2=np.random.randn(2,2)    #negative numbers also printing
print(rand2)

[[ 0.59973868 -0.99269601]
 [ 1.35502113 -0.04196095]]


In [ ]:
rand_int=np.random.randint(0,10,size=[5,3])
print(rand_int)

[[2 5 5]
 [3 7 7]
 [7 5 0]
 [7 0 2]
 [1 8 3]]


NumPy Matrix Multiplication with np.matmul()

In [ ]:
a=[[1,2,4],[4,5,5]]
h=[[5,6,6],[0,1,6]]
f=[[6,7,5],[4,1,2]]
print(np.matmul((a,h,f)))


TypeError: matmul() takes from 2 to 3 positional arguments but 1 were given

In [ ]:
a=[[1,2,3],[5,6,7]]
b=[[5],[1],[0]]
print(np.matmul(a,b))

[[ 7]
 [31]]


In [ ]:
np.linalg.det(a)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
a=[[1,2],[3,4]]
b=[[7,8],[9,6]]
print(np.matmul(a,b))

[[25 20]
 [57 48]]


In [ ]:
np.linalg.det(b)

np.float64(-30.000000000000014)

In [ ]:
z=np.zeros((8,8))
print(z)

z[1::2,::2]=1
z[::2,1::2]=1

print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
np_array=np.array(range(0,11))
np_array + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
temp=np.array([1,2,3,4,5])
pressure=temp*2+5

In [ ]:
print(pressure)

[ 7  9 11 13 15]


In [ ]:
print("Printing Array")

first_array=np.empty([4,2],dtype=np.uint16)

print(first_array)

print("Printing Numpy Array attributes")
print(f'array shape is {first_array.shape}')
print(f'Array dimensions are {first_array.ndim}')
print(f'length of each element of array in bytes is {first_array.itemsize}')

Printing Array
[[59280  6663]
 [  360     0]
 [    0     0]
 [    0     0]]
Printing Numpy Array attributes
array shape is (4, 2)
Array dimensions are 2
length of each element of array in bytes is 2


In [ ]:
print('creating 5*2 array using numpy.arange')

a=np.arange(100,200,10)

print(a)

b=a.reshape(5,2)
print(b)

creating 5*2 array using numpy.arange
[100 110 120 130 140 150 160 170 180 190]
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [ ]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
b=sampleArray.reshape(3,3)
print('printing input array')
print(b)

print(f'printing array of items in the third column from all rows {sampleArray[0::1,2]}')

new=sampleArray[...,2]
new

printing input array
[[11 22 33]
 [44 55 66]
 [77 88 99]]
printing array of items in the third column from all rows [33 66 99]


array([33, 66, 99])

In [ ]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print('input sample array')
print(sampleArray)

print('printing array of odd rows and even colums')
new=sampleArray[::2,1::2]
print(new)

input sample array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
printing array of odd rows and even colums
[[ 6 12]
 [30 36]
 [54 60]]


In [ ]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

print('addition of two array')
c=(np.add(arrayOne,arrayTwo))
print(c)

print('result array after calculating the square root of all elements')
d=np.square(c)
print(d)

addition of two array
[[20 39 33]
 [25 25 28]]
result array after calculating the square root of all elements
[[ 400 1521 1089]
 [ 625  625  784]]


In [ ]:
a=np.arange(10,34)
print('creating 8*3 array using numpy arange')
c=a.reshape(8,3)
print(c)


print('dividing 8*3 arrays into 4 subarrays ')
d=np.split(c,4)
print(d)


creating 8*3 array using numpy arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
dividing 8*3 arrays into 4 subarrays 
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print('printing original array')
print(sampleArray)

sampleArraycol=sampleArray[:,sampleArray[1,:].argsort()]
print('sorting original array by second column')
print(sampleArraycol)

samplearrayrow=sampleArray[sampleArray[:,1].argsort()]
print('printing original array by second row')
print(samplearrayrow)

printing original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
sorting original array by second column
[[73 43 34]
 [12 22 82]
 [66 94 53]]
printing original array by second row
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print('printing original Array')

print('printing amin of axis 1')
print(np.min(sampleArray,axis=1))

print('printing amax of axis 0')
print(np.max(sampleArray,axis=0))

printing original Array
printing amin of axis 1
[34 12 53]
printing amax of axis 0
[82 94 73]


In [ ]:
def fibonacci_series(num):
    if num == 0:
        return "Zero"
    elif num == 1:
        return "0"
    elif num < 0:
        return "Invalid number"
    else:
        series = []
        a, b = 0, 1
        for _ in range(num):
            series.append(a)
            a, b = b, a + b
        return " ".join(map(str, series))
print("Input: 10")
print("Output:", fibonacci_series(10))
print("Input: 15")
print("Output:", fibonacci_series(15))    


Input: 10
Output: 0 1 1 2 3 5 8 13 21 34
Input: 15
Output: 0 1 1 2 3 5 8 13 21 34 55 89 144 233 377


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print("printing original Array")
print(sampleArray)

print('Array after deleting column 2 on axis1')
sampleArray=np.delete(sampleArray,1,axis=1)
print(sampleArray)

arr=np.array([[10,10,10]])
print('array after inserting column 2 on axis1')
sampleArray=np.insert(sampleArray,1,arr,axis=1)
print(sampleArray)

printing original Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis1
[[34 73]
 [82 12]
 [53 66]]
array after inserting column 2 on axis1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [ ]:
from IPython.display import Image
Image('C:\Users\Mounika Reddy\OneDrive\Desktop\python-logo.png', width=200,heigh=100)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (2820651204.py, line 2)

In [ ]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


ARRAY IS USED TO CREATE THE DIMENSIONS

In [ ]:
##array is used to create the dimensions

a=np.array([1,2,3,4,5])
print(a)
a.ndim  #keyword used for finding the dimensions

[1 2 3 4 5]


1

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
print(a)
a.ndim

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]


2

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[0,9,5],[8,7,6]])
print(a)

a.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 9 5]
 [8 7 6]]


2

In [ ]:
a=np.arange(1,11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=np.array([1,2,3,5])
a.ndim

1

In [ ]:
#1-D array

a=np.array([1,2,3])
a1=np.array([[1],[2]])
a2=np.array([[[1,2,3]]])

In [ ]:
print(a)
print(a1)
print(a2)

[1 2 3]
[[1]
 [2]]
[[[1 2 3]]]


In [ ]:
a.ndim


1

In [ ]:
a2.ndim

3

In [ ]:
a1.ndim

2

In [ ]:
#arange
a=np.arange(1,10)
print(a)
a.ndim

[1 2 3 4 5 6 7 8 9]


1

In [ ]:
a=np.arange(1,10,2)  #last parameter gives step size
print(a)

[1 3 5 7 9]


In [ ]:
a=np.arange(1,15,3)
print(a)

[ 1  4  7 10 13]


In [ ]:
#using data type

a=np.arange(1,10,dtype=int)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.arange(1,10,dtype=float)
print(a)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
a=np.arange(1,10,2,dtype=bool)
print(a)

TypeError: arange() is only supported for booleans when the result has at most length 2.

In [ ]:
#linspace
a=np.linspace(1,30,1)
print(a)


[1.]


In [ ]:
a=np.linspace(1,30,6)
print(a)

[ 1.   6.8 12.6 18.4 24.2 30. ]


In [ ]:
#zeros

a=np.zeros([2,4],dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]]


In [ ]:
#checking 4*4 matrix
a=np.zeros([4,4],dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
a=np.ones([3,3],dtype=float)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#checking 4*4 matrix
a=np.ones([4,4],dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#range,start,stop
range(1,11)

range(1, 11)

In [ ]:
a=list(range(1,11))
a.ndim
a

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=np.arange(1,11)
a[5:]=60
print(a)

[ 1  2  3  4  5 60 60 60 60 60]


In [ ]:
#1-->D

a=np.array([1,2,3,4,5])
print(a.ndim)
print(a)

1
[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
#2---->D
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 3)

In [ ]:
a=np.arange(1,61)
print(a)
a.ndim

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]


1

In [ ]:
b=a.reshape(10,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [ ]:
b.shape

(3, 3)

In [ ]:
b.ndim

2

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [ ]:
b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
print(b)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [ ]:
print(m[1][2])

9


In [ ]:
m=np.arange(1,61).reshape(10,6)
print(m)
print(m[2][3])
print(m[6][3])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
16
40


In [ ]:
print(m.reshape(10,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [ ]:

print(m[4][5])

30


In [ ]:
print(m[3][2])

21


In [ ]:
m.ndim

2

In [ ]:
print(m[1][4])

11


In [ ]:
p=[1,2,3,4,5,6]
sum(p)

21

In [ ]:
z=np.arange(1,61).reshape(10,6)
print(z)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [ ]:
#for numpy axis =1 means rows---->axis=0 means columns 
a=np.sum(z,axis=1)
print(a)

[ 21  57  93 129 165 201 237 273 309 345]


In [ ]:
a1=np.sum(z,axis=0)
print(a1)


[280 290 300 310 320 330]


In [ ]:
z

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [ ]:
np.sum(z)


np.int64(1830)

In [ ]:
print(np.sum(z))

1830


In [ ]:
#3------>D


q=np.arange(1,61).reshape(10,6)
print(q)

print(f'finding dimensions:{q.ndim}')

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
finding dimensions:2


In [ ]:
#working with 3 dimensions data

s=np.arange(1,61).reshape(5,2,6)
s

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]],

       [[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48]],

       [[49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]]])

In [ ]:
s.ndim

3

In [ ]:
print(s[4][1][3])  #1 means down line in a row

58


In [ ]:
print(s[4][0][3])   #0 means up line in row

52


In [ ]:
print(s[3][0][5])

42


In [ ]:
s.shape

(5, 2, 6)

In [ ]:
s[2,1,3]

np.int64(34)

In [ ]:
print(s[1,1,5])

24


In [ ]:
np.random.randint(10,20)

10

In [ ]:
np.random.rand(3,4)  #3-->rows n 2--->col

array([[0.52875273, 0.0316079 , 0.64120241, 0.30699066],
       [0.61209849, 0.88008351, 0.25954101, 0.59332986],
       [0.73638917, 0.99362052, 0.72322963, 0.74160658]])

In [ ]:
print(np.random.randn(3,2))
print(np.random.randn(3,4))
#The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution.

[[ 0.26635053 -0.27230178]
 [-0.14327628 -0.53531164]
 [-0.98354788 -0.66649363]]
[[-1.0631561   0.45917546 -0.5358714   0.47542502]
 [-0.64567116  1.68778142 -0.17780212  0.75722126]
 [-0.2384154  -0.65464898 -1.27230427  1.29605604]]


In [ ]:
np.random.random((5,4))

array([[0.49070522, 0.63516444, 0.16728153, 0.55286273],
       [0.42265055, 0.38857407, 0.80411273, 0.73696712],
       [0.97185866, 0.07460418, 0.38587586, 0.78211745],
       [0.46966624, 0.46562353, 0.96134486, 0.27715807],
       [0.58331326, 0.02924957, 0.93115055, 0.22450854]])

In [ ]:
#sqrt
print(np.sqrt(4))

2.0


In [ ]:
print(np.sqrt(120))

10.954451150103322


In [ ]:
v=[2,3,4,5,7,98,100]
print(np.sqrt(v))

[ 1.41421356  1.73205081  2.          2.23606798  2.64575131  9.89949494
 10.        ]


In [ ]:
a=1
print(np.sin(a))

0.8414709848078965


In [ ]:
c=np.sin(v)
print(c)

[ 0.90929743  0.14112001 -0.7568025  -0.95892427  0.6569866  -0.57338187
 -0.50636564]


In [ ]:
a=45
print(np.sin(a))

0.8509035245341184


In [ ]:
a=45
print(np.cos(a))

0.5253219888177297


In [ ]:
d=np.cos(v)
print(d)

[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.75390225 -0.81928825
  0.86231887]


In [ ]:
a=np.arange(1,61).reshape(10,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [ ]:
b=np.arange(61,121).reshape(10,6)
b

array([[ 61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78],
       [ 79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102],
       [103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119, 120]])

In [ ]:
vstack=np.vstack((a,b))   #vertical stacking :place one array on top of the other: number of columns should match
print(vstack)

[[  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]
 [ 37  38  39  40  41  42]
 [ 43  44  45  46  47  48]
 [ 49  50  51  52  53  54]
 [ 55  56  57  58  59  60]
 [ 61  62  63  64  65  66]
 [ 67  68  69  70  71  72]
 [ 73  74  75  76  77  78]
 [ 79  80  81  82  83  84]
 [ 85  86  87  88  89  90]
 [ 91  92  93  94  95  96]
 [ 97  98  99 100 101 102]
 [103 104 105 106 107 108]
 [109 110 111 112 113 114]
 [115 116 117 118 119 120]]


In [ ]:
hstack=np.hstack((a,b))  #horizontal stacking one next to the other  number of the rows of the 2arrays should match
print(hstack)

[[  1   2   3   4   5   6  61  62  63  64  65  66]
 [  7   8   9  10  11  12  67  68  69  70  71  72]
 [ 13  14  15  16  17  18  73  74  75  76  77  78]
 [ 19  20  21  22  23  24  79  80  81  82  83  84]
 [ 25  26  27  28  29  30  85  86  87  88  89  90]
 [ 31  32  33  34  35  36  91  92  93  94  95  96]
 [ 37  38  39  40  41  42  97  98  99 100 101 102]
 [ 43  44  45  46  47  48 103 104 105 106 107 108]
 [ 49  50  51  52  53  54 109 110 111 112 113 114]
 [ 55  56  57  58  59  60 115 116 117 118 119 120]]


In [ ]:
hstack.shape

(10, 12)

In [ ]:
vstack.shape

(20, 6)

In [ ]:
#sum,max,min
a=[1,2,3,4,5,6]
print(np.sum(a))

21


In [ ]:
max(a)

6

In [ ]:
min(a)

1

In [ ]:
aa=np.diag([1,2,3,4,5,6])
aa

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
a=np.array([[1,2,3],[4,5,67]])
print(a)
a.ndim

[[ 1  2  3]
 [ 4  5 67]]


2

In [ ]:
##ravel changes any dimension to 1--->D dimension
aa=a.ravel()
print(aa)
aa.ndim

[ 1  2  3  4  5 67]


1

In [ ]:
a.ndim

2

In [ ]:
a=np.array([[1,2,3,4],[43,76,87,20]])
print(a)
a.ndim

[[ 1  2  3  4]
 [43 76 87 20]]


2

In [ ]:
a.T

array([[ 1, 43],
       [ 2, 76],
       [ 3, 87],
       [ 4, 20]])

In [ ]:
a.ndim

2

In [ ]:
#absolute value

a=np.abs(-100)

print(a)

100


In [ ]:
#concatenate

a=np.array([[1,2,3],[4,5,6]])

b=np.array([[4,7,8],[9,8,2]])

print(a)

print()

print(b)

print()

c=np.concatenate((a,b))
print(c)

[[1 2 3]
 [4 5 6]]

[[4 7 8]
 [9 8 2]]

[[1 2 3]
 [4 5 6]
 [4 7 8]
 [9 8 2]]


In [ ]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
n=np.zeros((4,4))
print(n)
print()
print(n.itemsize * n.size)
print()
print('%d bytes'%(n.size*n.itemsize))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

128

128 bytes


In [ ]:
a=9
b=6
a=a^b
b=a^b
a=a^b
print(a)
print(b)

6
9


In [ ]:
a=4
b=5
a=a+b
b=a-b
a=a-b
print(a)
print(b)

5
4


In [ ]:
a,b=swap(a,b)

NameError: name 'swap' is not defined

In [ ]:
a=np.eye(2,2,dtype=int)  #eye means identity matrix
print(a)

[[1 0]
 [0 1]]


In [ ]:
a=np.eye(5,5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#transpose

a=np.array([[1,2,3],[4,5,6],[7,6,4]])
print(a)
a.T

[[1 2 3]
 [4 5 6]
 [7 6 4]]


array([[1, 4, 7],
       [2, 5, 6],
       [3, 6, 4]])

In [ ]:
a=np.array([[1,2],[2,3]])
a.T

array([[1, 2],
       [2, 3]])

In [ ]:
#reshaping

arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
arr=np.arange(20)
print(arr)

arr.reshape(5,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
#let's compare two arrays values to get the maximum of each.
x=np.random.randn(8)
print(x)

y=np.random.randn(8)
print(y)

np.maximum(x,y)

[ 0.42677461 -0.51566385 -0.07036752  0.95610702  0.39005766  0.35460095
 -0.9213908  -1.13376174]
[ 0.98564737 -0.12772258  1.10626533 -0.8113525  -1.50738873  0.91615896
 -0.96155875 -1.13393616]


array([ 0.98564737, -0.12772258,  1.10626533,  0.95610702,  0.39005766,
        0.91615896, -0.9213908 , -1.13376174])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))

print(np.sum(a,axis=0))

print(np.sum(a,axis=1))

21
[5 7 9]
[ 6 15]


In [ ]:
#determine the inner product of two vectors

a1d=np.array([1,2])
b1d=np.array([7,8])
print(a1d.dot(b1d))

print()

print(np.dot(a1d,b1d))


23

23


In [ ]:
#determine the dot product of two matrices

a=np.array([[1,2],[4,5]])

b=np.array([[4,5],[9,8]])

print(a.dot(b))

print()

print(np.dot(a,b))

[[22 21]
 [61 60]]

[[22 21]
 [61 60]]


In [ ]:
a=np.array([[1,2,3],[8,9,7],[9,0,4],[87,45,7]])

print(a)

print(a.ndim)

print(a.shape)

print(a.shape)

[[ 1  2  3]
 [ 8  9  7]
 [ 9  0  4]
 [87 45  7]]
2
(4, 3)
(4, 3)


In [ ]:
a=np.arange(1,82).reshape(3,3,9)

In [ ]:
print(a)

[[[ 1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18]
  [19 20 21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34 35 36]
  [37 38 39 40 41 42 43 44 45]
  [46 47 48 49 50 51 52 53 54]]

 [[55 56 57 58 59 60 61 62 63]
  [64 65 66 67 68 69 70 71 72]
  [73 74 75 76 77 78 79 80 81]]]


In [ ]:
a[2][1][5]

np.int64(69)

In [ ]:
an_array=np.array([1,22,333])
print(type(an_array))

<class 'numpy.ndarray'>


In [ ]:
print(an_array)

[  1  22 333]


In [ ]:
an_array.shape

(3,)

In [ ]:
print(an_array[0],an_array[1],an_array[2])

1 22 333


In [ ]:
an_array[0]=8888
print(an_array)

[8888   22  333]


**A rank 2 ndarray is one with two dimensions. Notice the format below of [ [row] , [row] ]. 2 dimensional arrays are great for representing matrices which are often useful in data science.**


In [ ]:
#how to create a rank 2 numpy:

another =np.array([[1,2,3],[4,5,6]])
print(another)
print()

print(f'the shape is 2 rows 3 columns :{another.shape}')

print(f'acessing elements [0,0] [0,1] [1,0] of the ndarray : {another[0,0],another[0,1],another[1,0]}')


[[1 2 3]
 [4 5 6]]

the shape is 2 rows 3 columns :(2, 3)
acessing elements [0,0] [0,1] [1,0] of the ndarray : (np.int64(1), np.int64(2), np.int64(4))


There are many way to create numpy arrays:

Here we create a number of different size arrays with different shapes and different pre-filled values. numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [ ]:
#create a  2*2 array of zero matrix

a=np.zeros((2,2),dtype=int)
a

array([[0, 0],
       [0, 0]])

FULL


In [ ]:
#cretaing a  2*2 matrix array filled with 9.0

a=np.full((2,2),9,dtype=float)
a

array([[9., 9.],
       [9., 9.]])

In [ ]:
#creating a 2*2 matrix with the diagonals 1s and the others 0

a=np.eye(2,2,dtype=int)
a

array([[1, 0],
       [0, 1]])

In [ ]:
#cretae an numpy array of ones
a=np.ones((2,2),dtype=int)
a

array([[1, 1],
       [1, 1]])

In [ ]:
print(a.shape)

(2, 2)


In [ ]:
print(a[0,1])

1


In [ ]:
#creta an array of random floats between 0 and 1

ex5=np.random.random((2,2))

In [ ]:
print(ex5)

[[0.67110879 0.33540878]
 [0.70737382 0.19040283]]


ARRAY INDEXING

SLICE INDEXING

Similar to use of slice indexing with lists and strings ,we can use slice indexing to pull out sub reginons of ndarrays

In [45]:
#rank 2 array shape of 3*4

w=np.array([[1,2,3,4],[66,77,88,9],[9,5,4,3]])
print(w)

[[ 1  2  3  4]
 [66 77 88  9]
 [ 9  5  4  3]]


In [50]:
a=w[1,0:]

In [51]:
a

array([66, 77, 88,  9])

In [54]:
b=a[-1]

In [55]:
b

np.int64(9)

Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [60]:
w

array([[ 1,  2,  3,  4],
       [66, 77, 88,  9],
       [ 9,  5,  4,  3]])

In [58]:
a_slice=w[:2,1:3]   #starting point":endingpoint2(n-1),1(startingpoint) : 3(ending point(n-1))

In [59]:
a_slice

array([[ 2,  3],
       [77, 88]])

In [64]:
a=w[1:3,1:3]

In [65]:
a

array([[77, 88],
       [ 5,  4]])

In [63]:
w[2][3]

np.int64(3)

Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.When you modify a slice, you actually modify the underlying array.

In [66]:
w

array([[ 1,  2,  3,  4],
       [66, 77, 88,  9],
       [ 9,  5,  4,  3]])

In [67]:
a_slice

array([[ 2,  3],
       [77, 88]])

In [68]:
a

array([[77, 88],
       [ 5,  4]])

In [69]:
print(f'before : {w[0,1]}')
a_slice[0,0]=1000
print(f'after: {w[0,1]}')

before : 2
after: 1000
